name: Create Release
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'resources2.s2z'
        directory: 'game'
        custom: '-acf'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "game/resources2.s2z"
        tag: "2024-09-09-${{ github.sha }}"
        generateReleaseNotes: true
